"""
This type stub file was generated by pyright.
"""

import logging
import signal

HANDLED_SIGNALS = (signal.SIGINT, signal.SIGTERM)
logger = logging.getLogger("uvicorn.error")

class Multiprocess:
    def __init__(self, config, target, sockets) -> None: ...
    def signal_handler(self, sig, frame):
        """
        A signal handler that is registered with the parent process.
        """
        ...
    def run(self): ...
    def startup(self): ...
    def shutdown(self): ...
