"""
This type stub file was generated by pyright.
"""

import logging
from uvicorn.supervisors.basereload import BaseReload

logger = logging.getLogger("uvicorn.error")

class StatReload(BaseReload):
    def __init__(self, config, target, sockets) -> None: ...
    def should_restart(self): ...
    def iter_py_files(self): ...
