"""
This type stub file was generated by pyright.
"""

import logging

TRACE_LOG_LEVEL = 5

class ColourizedFormatter(logging.Formatter):
    """
    A custom log formatter class that:

    * Outputs the LOG_LEVEL with an appropriate color.
    * If a log call includes an `extras={"color_message": ...}` it will be used
      for formatting the output, instead of the plain text message.
    """

    level_name_colors = ...
    def __init__(self, fmt=..., datefmt=..., style=..., use_colors=...) -> None: ...
    def color_level_name(self, level_name, level_no): ...
    def should_use_colors(self): ...
    def formatMessage(self, record): ...

class DefaultFormatter(ColourizedFormatter):
    def should_use_colors(self): ...

class AccessFormatter(ColourizedFormatter):
    status_code_colours = ...
    def get_status_code(self, status_code: int): ...
    def formatMessage(self, record): ...
