"""
This type stub file was generated by pyright.
"""

from amqpstorm.exception import AMQPError

class ApiError(AMQPError):
    """Management Api Error"""

    def __init__(self, message=..., *args, **kwargs) -> None: ...
    def __str__(self) -> str: ...

class ApiConnectionError(AMQPError):
    """Management Api Connection Error"""

    ...
