"""
This type stub file was generated by pyright.
"""

from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any, Dict

class Connection(ABC):
    @abstractmethod
    def __init__(self, url: str) -> None: ...
    @abstractmethod
    def get(self, path: str = ..., query: Dict[str, Any] = ...) -> Response: ...
    @abstractmethod
    def post(
        self,
        path: str = ...,
        data: Any = ...,
        headers: Dict[str, str] = ...,
        query: Dict[str, Any] = ...,
    ) -> Response: ...
    @abstractmethod
    def put(
        self,
        path: str = ...,
        data: Any = ...,
        headers: Dict[str, str] = ...,
        query: Dict[str, Any] = ...,
    ) -> Response: ...
    @abstractmethod
    def delete(self, path: str, query: Dict[str, Any] = ...) -> Response: ...
    @abstractmethod
    def head(self, path: str, query: Dict[str, Any] = ...) -> Response: ...

class Response(ABC):
    @property
    @abstractmethod
    def status(self) -> int: ...
    @abstractmethod
    def get_data(self) -> Any: ...
    @abstractmethod
    def get_headers(self) -> Any: ...
