"""
This type stub file was generated by pyright.
"""

from http.client import HTTPResponse
from . import Connection, Response
from typing import Any, Dict

class UrllibConn(Connection):
    def __init__(self, url: str = ..., timeout: int = ...) -> None: ...
    def get(self, path: str = ..., query: Dict[str, Any] = ...): ...
    def post(
        self,
        path: str = ...,
        data: Any = ...,
        headers: Dict[str, str] = ...,
        query: Dict[str, Any] = ...,
    ): ...
    def put(
        self,
        path: str = ...,
        data: Any = ...,
        headers: Dict[str, str] = ...,
        query: Dict[str, Any] = ...,
    ): ...
    def delete(self, path: str, query: Dict[str, Any] = ...): ...
    def head(self, path: str, query: Dict[str, Any] = ...): ...
    def request(
        self,
        path: str,
        method: str = ...,
        data: Any = ...,
        headers: Dict[str, str] = ...,
        query: Dict[str, Any] = ...,
    ) -> Response: ...

class UrllibResponse(Response):
    def __init__(self, resp: HTTPResponse) -> None: ...
    @property
    def status(self): ...
    def get_data(self) -> Any: ...
    def get_headers(self): ...

class UrllibResponseError(UrllibResponse):
    def __init__(self, resp: urllib.error.HTTPError) -> None: ...
