"""
This type stub file was generated by pyright.
"""

import logging
from amqpstorm.channel import Channel
from amqpstorm.connection import Connection
from amqpstorm.uri_connection import UriConnection
from amqpstorm.message import Message
from amqpstorm.exception import (
    AMQPChannelError,
    AMQPConnectionError,
    AMQPError,
    AMQPInvalidArgument,
    AMQPMessageError,
)

"""AMQPStorm."""
__version__ = ...
__author__ = ...
