"""
This type stub file was generated by pyright.
"""

"""AMQPStorm Connection.Channel0."""
LOGGER = ...

class Channel0:
    """Internal Channel0 handler."""

    def __init__(self, connection, client_properties=...) -> None: ...
    def on_frame(self, frame_in):  # -> None:
        """Handle frames sent to Channel0.

        :param frame_in: Amqp frame.
        :return:
        """
        ...
    def send_close_connection(self):  # -> None:
        """Send Connection Close frame.

        :return:
        """
        ...
    def send_heartbeat(self):  # -> None:
        """Send Heartbeat frame.

        :return:
        """
        ...
