"""
This type stub file was generated by pyright.
"""

"""Python 2/3 Compatibility layer."""
RANGE = range

class DummyException(Exception):
    """
    Never raised by anything.

    This is used in except blocks if the intended
    exception cannot be imported.
    """

    ...

SSL_CERT_MAP = ...
SSL_VERSIONS = ...
SSL_OPTIONS = ...

def get_default_ssl_version():  # -> int | None:
    """Get the highest support TLS version, if none is available, return None.

    :rtype: bool,None
    """
    ...

DEFAULT_SSL_VERSION = ...
SSL_SUPPORTED = ...
if SSL_SUPPORTED:
    SSL_CERT_MAP = ...
    SSLWantReadError = ...
else:
    SSLWantReadError = ...

def is_string(obj):  # -> bool:
    """Is this a string.

    :param object obj:
    :rtype: bool
    """
    ...

def is_integer(obj):  # -> bool:
    """Is this an integer.

    :param object obj:
    :return:
    """
    ...

def try_utf8_decode(value):  # -> str | bytes:
    """Try to decode an object.

    :param value:
    :return:
    """
    ...

def patch_uri(uri):
    """If a custom uri schema is used with python 2.6 (e.g. amqps),
    it will ignore some of the parsing logic.

        As a work-around for this we change the amqp/amqps schema
        internally to use http/https.

    :param str uri: AMQP Connection string
    :rtype: str
    """
    ...
