"""
This type stub file was generated by pyright.
"""

"""AMQPStorm Connection.Heartbeat."""
LOGGER = ...

class Heartbeat:
    """Internal Heartbeat handler."""

    def __init__(self, interval, send_heartbeat_impl, timer=...) -> None: ...
    def register_read(self):  # -> None:
        """Register that a frame has been received.

        :return:
        """
        ...
    def register_write(self):  # -> None:
        """Register that a frame has been sent.

        :return:
        """
        ...
    def start(self, exceptions):  # -> bool:
        """Start the Heartbeat Checker.

        :param list exceptions:
        :return:
        """
        ...
    def stop(self):  # -> None:
        """Stop the Heartbeat Checker.

        :return:
        """
        ...
