"""
This type stub file was generated by pyright.
"""

"""AMQPStorm Connection.IO."""
EMPTY_BUFFER = ...
LOGGER = ...
POLL_TIMEOUT = ...

class Poller:
    """Socket Read Poller."""

    def __init__(self, fileno, exceptions, timeout=...) -> None: ...
    @property
    def fileno(self):
        """Socket Fileno.

        :return:
        """
        ...
    @property
    def is_ready(self):  # -> bool:
        """Is Socket Ready.

        :rtype: tuple
        """
        ...

class IO:
    """Internal Input/Output handler."""

    def __init__(self, parameters, exceptions=..., on_read_impl=...) -> None: ...
    def close(self):  # -> None:
        """Close Socket.

        :return:
        """
        ...
    def open(self):  # -> None:
        """Open Socket and establish a connection.

        :raises AMQPConnectionError: Raises if the connection
                                     encountered an error.
        :return:
        """
        ...
    def write_to_socket(self, frame_data):  # -> None:
        """Write data to the socket.

        :param str frame_data:
        :return:
        """
        ...
