"""
This type stub file was generated by pyright.
"""

from .connections import Connection
from .db import Database
from typing import Callable, List

class Client:
    """Main class to connect to Database"""

    def __init__(
        self, url: str, connection_engine: Callable[[str], Connection] = ...
    ) -> None: ...
    def get_db(self, name: str):
        """Return database instance

        Args:
            name (str): Database name

        Returns:
            class: instance of pycouchdb.db.Database:
        """
        ...
    def create(self, db_name: str):
        """
        Creates a new database.
        The database name {db} must be composed by following next rules:
        Name must begin with a lowercase letter (a-z)
        Lowercase characters (a-z)
        Digits (0-9)
        Any of the characters _, $, (, ), +, -, and /.

        Args:
            name (str):  The name of new Db.

        Returns:
            dict:  status

        Raises:
            ServerError

        """
        ...
    def delete(self, db_name: str):
        """Deletes the specified database, and all the documents and attachments contained within it.

        Args:
            db_name (str): Database name

        Returns:
            dict:  status

        Raises:
            ServerError
        """
        ...
    def list_database_names(self) -> List[str]:
        """List of all databases names

        Returns:
            list:   databases names
        """
        ...
    def __iter__(self): ...
    def __getitem__(self, db_name: str) -> Database: ...
    def __contains__(self, item: str) -> bool: ...
    def __repr__(self) -> str: ...
