"""
This type stub file was generated by pyright.
"""

PLACEHOLDER_FORMAT = {
    "body": "<{length} bytes>",
    "bytes": "<{length} bytes>",
    "text": "<{length} chars>",
    "headers": "<...>",
}
TRACE_LOG_LEVEL = 5

def message_with_placeholders(message):
    """
    Return an ASGI message, with any body-type content omitted and replaced
    with a placeholder.
    """
    ...

class MessageLoggerMiddleware:
    def __init__(self, app) -> None: ...
    async def __call__(self, scope, receive, send): ...
