"""
This type stub file was generated by pyright.
"""

"""
This middleware can be used when a known proxy is fronting the application,
and is trusted to be properly setting the `X-Forwarded-Proto` and
`X-Forwarded-For` headers with the connecting client information.

Modifies the `client` and `scheme` information so that they reference
the connecting client, rather that the connecting proxy.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#Proxies
"""

class ProxyHeadersMiddleware:
    def __init__(self, app, trusted_hosts=...) -> None: ...
    async def __call__(self, scope, receive, send): ...
